apiVersion: v1
kind: Service
metadata:
  name: feedback-service
spec:
  selector:
    app: feedback
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Should match the container port in the deployment
  type: LoadBalancer  # Use "ClusterIP" if internal or "NodePort" for external access
